http:
  enabled: false

input:
  generate:
    interval: "1s"
    mapping: |
      root = {
        "locations": [
          {"name": "Seattle", "state": "WA"},
          {"name": "New York", "state": "NY"},
          {"name": "Bellevue", "state": "WA"},
          {"name": "Olympia", "state": "WA"}
        ]
      }

pipeline:
  processors:
    - bloblang: '{"Cities":this.locations.filter(this.state == "WA").map_each(this.name).sort().join(", ")}'

output:
  kafka:
    addresses: [ localhost:9092 ]
    topic: a_results
    client_id: a_client
    max_in_flight: 100
    inject_tracing_map: 'meta = this'

tracer:
  jaeger:
    agent_address: 'localhost:6831'
    tags:
      pipeline: my_tracing_example
